
export const AVAILABLE_COMMANDS = [
  'go <direction or location name>',
  'goto <object or npc>',
  'move to <object or npc>',
  'shift to <object or npc>',
  'examine <object or item>',
  'open <object>',
  'look at <object or item>',
  'look around',
  'look behind <object>',
  'take <item>',
  'put <item> in pocket',
  'add <item> to inventory',
  'take <item> with me',
  'grab <item>',
  'pick up <item>',
  'use <item> on <object>',
  'talk to <npc>',
  'inventory',
  'help',
  'password for <object> "<phrase>"',
  'say "<phrase>" to <object>',
  'say "<phrase>"',
  'enter "<phrase>" for <object>',
  'enter "<phrase>"',
  'goodbye',
  'read article',
  'watch video',
  'exit',
  'close',
  'invalid',
];
