
export const AVAILABLE_COMMANDS = [
  'go <direction or location name>',
  'examine <object or item>',
  'open <object>',
  'look at <object or item>',
  'look around',
  'look behind <object>',
  'take <item>',
  'use <item> on <object>',
  'talk to <npc>',
  'inventory',
  'help',
  'password for <object> "<phrase>"',
  'say "<phrase>" to <object>',
  'enter "<phrase>" for <object>',
  'goodbye',
  'read article',
  'watch video',
  'exit',
  'close',
  'restart',
  'invalid',
];
